version: '2'
services:
  profile_test:    
    image: aksenchyk/fm-profile:build
    environment:
      # codecov.io requires this variables
      - CIRCLE_BUILD_NUM=$CIRCLE_BUILD_NUM  
      - CIRCLECI=$CIRCLECI
      - CIRCLE_BUILD_NUM = $CIRCLE_BUILD_NUM
      - CIRCLE_NODE_INDEX=$CIRCLE_NODE_INDEX
      - CIRCLE_SHA1=$CIRCLE_SHA1
      - CIRCLE_BRANCH=$CIRCLE_BRANCH
      - CIRCLE_PR_NUMBER=$CIRCLE_PR_NUMBER
      - CIRCLE_PROJECT_USERNAME=$CIRCLE_PROJECT_USERNAME
      - CIRCLE_PROJECT_REPONAME=$CIRCLE_PROJECT_REPONAME
      - CIRCLE_ARTIFACTS=$CIRCLE_ARTIFACTS
    env_file:
      - ./test_.env  
    command: npm run test 
   